const categoryTypes = {
  // Get categories
  "GET_CATEGORY_REQUEST": "GET_CATEGORY_REQUEST",
  "GET_CATEGORY_SUCCESS": "GET_CATEGORY_SUCCESS",
  "GET_CATEGORY_FAILURE": "GET_CATEGORY_FAILURE",

  // Add new category
  "ADD_NEW_CATEGORY_REQUEST": "ADD_NEW_CATEGORY_REQUEST",
  "ADD_NEW_CATEGORY_SUCCESS": "ADD_NEW_CATEGORY_SUCCESS",
  "ADD_NEW_CATEGORY_FAILURE": "ADD_NEW_CATEGORY_FAILURE",

  // Update category
  "UPDATE_CATEGORY_REQUEST": "UPDATE_CATEGORY_REQUEST",
  "UPDATE_CATEGORY_SUCCESS": "UPDATE_CATEGORY_SUCCESS",
  "UPDATE_CATEGORY_FAILURE": "UPDATE_CATEGORY_FAILURE",

  // Delete category
  "DELETE_CATEGORY_REQUEST": "DELETE_CATEGORY_REQUEST",
  "DELETE_CATEGORY_SUCCESS": "DELETE_CATEGORY_SUCCESS",
  "DELETE_CATEGORY_FAILURE": "DELETE_CATEGORY_FAILURE",
}

export default categoryTypes;
