const commentTypes = {
    // Clear comment reducer
    "CLEAR_COMMENTS_LIST": "CLEAR_COMMENTS_LIST",

    // Get comments
    "GET_COMMENTS_REQUEST": "GET_COMMENTS_REQUEST",
    "GET_COMMENTS_SUCCESS": "GET_COMMENTS_SUCCESS",
    "GET_COMMENTS_FAILURE": "GET_COMMENTS_FAILURE",

    // Update comment status
    "EDIT_COMMENT_REQUESET": "EDIT_COMMENT_REQUESET",
    "EDIT_COMMENT_SUCCESS": "EDIT_COMMENT_SUCCESS",
    "EDIT_COMMENT_FAILURE": "EDIT_COMMENT_FAILURE",
}

export default commentTypes;
