const errorTypes = {
    "GET_ERRORS_LIST_REQUEST": "GET_ERRORS_LIST_REQUEST",
    "GET_ERRORS_LIST_SUCCESS": "GET_ERRORS_LIST_SUCCESS",
    "GET_ERRORS_LIST_FAILURE": "GET_ERRORS_LIST_FAILURE",

    "EDIT_ERROR_REQUEST": "EDIT_ERROR_REQUEST",
    "EDIT_ERROR_SUCCESS": "EDIT_ERROR_SUCCESS",
    "EDIT_ERROR_FAILURE": "EDIT_ERROR_FAILURE",

    "DELETE_ERROR_REQUEST": "DELETE_ERROR_REQUEST",
    "DELETE_ERROR_SUCCESS": "DELETE_ERROR_SUCCESS",
    "DELETE_ERROR_FAILURE": "DELETE_ERROR_FAILURE",
};
  
export default errorTypes;