const reviewTypes = {
    // Clear review reducer
    "CLEAR_REVIEWS_LIST": "CLEAR_REVIEWS_LIST",

    // Get reviews
    "GET_REVIEWS_REQUEST": "GET_REVIEWS_REQUEST",
    "GET_REVIEWS_SUCCESS": "GET_REVIEWS_SUCCESS",
    "GET_REVIEWS_FAILURE": "GET_REVIEWS_FAILURE",

    // Edit review
    "EDIT_REVIEW_REQUEST": "EDIT_REVIEW_REQUEST",
    "EDIT_REVIEW_SUCCESS": "EDIT_REVIEW_SUCCESS",
    "EDIT_REVIEW_FAILURE": "EDIT_REVIEW_FAILURE",
}

export default reviewTypes;
