const searchType = {
    "GET_SEARCHES_LIST_REQUEST": "GET_SEARCHES_LIST_REQUEST",
    "GET_SEARCHES_LIST_SUCCESS": "GET_SEARCHES_LIST_SUCCESS",
    "GET_SEARCHES_LIST_FAILURE": "GET_SEARCHES_LIST_FAILURE",
};

export default searchType;