const tagTypes = {
  // Get tags
  "GET_TAGS_REQUEST": "GET_TAGS_REQUEST",
  "GET_TAGS_SUCCESS": "GET_TAGS_SUCCESS",
  "GET_TAGS_FAILURE": "GET_TAGS_FAILURE",

  // Add new tag
  "ADD_NEW_TAG_REQUEST": "ADD_NEW_TAG_REQUEST",
  "ADD_NEW_TAG_SUCCESS": "ADD_NEW_TAG_SUCCESS",
  "ADD_NEW_TAG_FAILURE": "ADD_NEW_TAG_FAILURE",

  // Update tag
  "UPDATE_TAG_REQUEST": "UPDATE_TAG_REQUEST",
  "UPDATE_TAG_SUCCESS": "UPDATE_TAG_SUCCESS",
  "UPDATE_TAG_FAILURE": "UPDATE_TAG_FAILURE",

  // Delete tag
  "DELETE_TAG_REQUEST": "DELETE_TAG_REQUEST",
  "DELETE_TAG_SUCCESS": "DELETE_TAG_SUCCESS",
  "DELETE_TAG_FAILURE": "DELETE_TAG_FAILURE",
}

export default tagTypes;
