const userTypes = {
  "CLEAR_USER_REDUCER":"CLEAR_USER_REDUCER",
  "UPDATE_USERNAME": "UPDATE_USERNAME",

  // Login
  "LOGIN_REQUEST": 'LOGIN_REQUEST',
  "LOGIN_SUCCESS": 'LOGIN_SUCCESS',
  "LOGIN_FAILURE": 'LOGIN_FAILURE',

  // Get User By Id
  "GET_MYSELF_REQUEST": "GET_MYSELF_REQUEST",
  "GET_MYSELF_SUCCESS": "GET_MYSELF_SUCCESS",
  "GET_MYSELF_FAILURE": "GET_MYSELF_FAILURE",

  // Get users list
  "GET_USERS_LIST_REQUEST": "GET_USERS_LIST_REQUEST",
  "GET_USERS_LIST_SUCCESS": "GET_USERS_LIST_SUCCESS",
  "GET_USERS_LIST_FAILURE": "GET_USERS_LIST_FAILURE",

  // Get single user
  "GET_SINGLE_USER_REQUEST": "GET_SINGLE_USER_REQUEST",
  "GET_SINGLE_USER_SUCCESS": "GET_SINGLE_USER_SUCCESS",
  "GET_SINGLE_USER_FAILURE": "GET_SINGLE_USER_FAILURE",

  // Edit user
  "EDIT_USER_REQUEST": "EDIT_USER_REQUEST",
  "EDIT_USER_SUCCESS": "EDIT_USER_SUCCESS",
  "EDIT_USER_FAILURE": "EDIT_USER_FAILURE",

  // Log out
  "LOGOUT_REQUEST": "LOGOUT_REQUEST",
  "LOGOUT_SUCCESS": "LOGOUT_SUCCESS",
  "LOGOUT_FAILURE": "LOGOUT_FAILURE",

};

export default userTypes;
